---
- name: "check OS compatibility and ansible version"
  assert:
    that:
      - ansible_version.full is version('2.8', '>=')
      - ( ansible_os_family == 'RedHat' and ansible_distribution_major_version|int in [7, 8] ) or
        ( ansible_os_family == 'Debian' and ansible_distribution_major_version|int in [9, 10] )
      - ansible_service_mgr == "systemd"
    quiet: yes
...
