---
# `async="{{ iptables_apply__rollback_timeout }}"` and `poll=0` are mandatory
# parameters to ensure ansible detaches itself from the script and the script
# still runs in background time enough.
- name: "apply iptables ruleset and wait for confirmation"
  iptables_state:
    state: restored
    path: "{{ iptables_apply__path_buffer }}"
    back: "{{ iptables_apply__path_backup }}"
    noflush: "{{ iptables_apply__template_noflush if iptables_apply__action == 'template' else omit }}"
    timeout: "{{ iptables_apply__rollback_timeout }}"
  async: "{{ iptables_apply__rollback_timeout }}"
  poll: 0
  register: iptables_apply__restored
