---
# Initialize iptables so the output of iptables-save will not be empty.
# Otherwise, rolling back to previous state will not work when restoring this
# state from nothing.


# The starting point for atomic changes with actions `append`, `insert` or
# `delete`.  Actions `template` and `flush` will overwrite it entirely.
- name: "save initial state of the firewall into temporary buffer"
  iptables_state:
    state: saved
    path: "{{ iptables_apply__path_buffer }}"
    table: "{{ omit if iptables_apply__action in ['template','flush'] else 'filter' }}"
  register: iptables_apply__saved_state
  failed_when:
    - iptables_apply__saved_state.initial_state | length < 7
