---
- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: confirm applied ruleset as persistent
  command: "service {{ iptables_apply__service }} save"
  args:
    warn: no
  when: iptables_ruleset is changed

- name: manage firewall service state and activation
  systemd:
    name: "{{ iptables_apply__service }}"
    enabled: "{{ iptables_apply__service_enabled }}"
    state: "{{ 'started' if iptables_apply__service_started else 'stopped' }}"
