---
# Initialize iptables so the output of iptables-save will not be empty.
# Otherwise, rolling back to previous state will not work when restoring this
# state from nothing.


- name: "ensure backup will not be empty"
  block:
    - import_tasks: iptables-init.yml

  rescue:
    - name: "initialize firewall from NULL state"
      command: iptables-restore
      args:
        stdin: |
          *filter
          :INPUT ACCEPT [0:0]
          :OUTPUT ACCEPT [0:0]
          :FORWARD ACCEPT [0:0]
          COMMIT
      changed_when: true

    - import_tasks: iptables-init.yml
