---
- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: confirm applied ruleset as persistent
  command: service netfilter-persistent save
  args:
    warn: no

- name: enable and start service
  systemd:
    name: netfilter-persistent
    enabled: yes
    state: started
