---
# Initialize iptables so the output of iptables-save will not be empty.
# Otherwise, rolling back to previous state will not work when restoring this
# state from nothing.


- name: "ensure backup will not be empty"
  block:
    - import_tasks: iptables-init.yml

  rescue:
    - name: "initialize firewall from NULL state"
      iptables:
        chain: "{{ iptables_apply_item }}"
        policy: ACCEPT
      loop: ["INPUT", "OUTPUT", "FORWARD"]
      loop_control:
        loop_var: iptables_apply_item

    - import_tasks: iptables-init.yml
