---
# To validate changes, we will switch connection plugin to be sure to not reuse
# a previous connection.
- name: get current connection plugin
  set_fact:
    initial_connection: "{{ ansible_connection }}"
  failed_when: "ansible_connection not in ['paramiko','ssh']"


# It will be used in case of rollback, and as the starting point for `append`,
# `insert` or `delete` actions.
- name: save initial state of the firewall
  shell: >
    iptables-save -t filter |
    tee {{ iptables_apply__path_backup }} {{
           iptables_apply__path_buffer if iptables_apply__action != 'template' else ''
        }}


# Do all the stuff using a template, or just delete/append/insert/update rules
- name: build iptables ruleset
  include_tasks: "iptables-{{ iptables_apply__action }}.yml"


# Actually apply the ruleset and try to confirm it.
- name: apply iptables ruleset
  include_tasks: iptables-apply.yml


# Save applied ruleset so it will be applied again after reboot.
- name: confirm applied ruleset as persistent
  include_tasks: "iptables-save_{{ ansible_os_family|lower }}.yml"
  when: iptables_apply__persist

