---
# Perform a safety check to ensure rollback will happen if needed, and also
# ensure the backup of initial ruleset is suitable for a rollback if needed
# (i.e. not an empty file).
- import_tasks: iptables-prepare.yml


# Do all the stuff using a template, or just delete/append/insert/update rules.
# Do not ever try to modify system state (iptables state) nor system files (in
# /etc) at this step.  All actions are performed against a temporary file, the
# 'buffer' (that is a copy of the 'backup', all created above).
- import_tasks: "rules-{{ iptables_apply__action }}.yml"


# Actually apply the ruleset and try to confirm it.
- import_tasks: iptables-apply.yml


# Save applied ruleset so it will be applied again after reboot.
- import_tasks: iptables-persist.yml


# And finally, ensure the service is started and enabled (or not).
- import_tasks: iptables-service.yml
