---
# We need to know the current rules in filter table to stat if template has to
# be applied or not. But we don't need to store the table in a file.
- import_tasks: iptables_state.yml
  vars:
    iptables_state__task_name: "get initial state of the firewall"


- name: "rewrite iptables buffer from scratch"
  template:
    src: "{{ iptables_apply__template }}"
    dest: "{{ iptables_apply__path_buffer }}"
  register: iptables_apply__ruleset
  when:
    - ( not iptables_apply__template_once | bool ) or
      ( not iptables_apply__template_mark in iptables_state__registered.initial_state )
...
