---
- name: "rewrite iptables ruleset's buffer from scratch"
  template:
    src: "{{ iptables_apply__template }}"
    dest: "{{ iptables_apply__path_buffer }}"
    validate: "iptables-restore --test %s"
  register: iptables_apply__ruleset
  when:
    - ( not iptables_apply__template_once|bool ) or
      ( not iptables_apply__template_mark in iptables_apply__saved_state.initial_state )
