---
- name: delete all rules and reset policies to 'ACCEPT' for all chains
  template:
    src: "{{ iptables_apply__flush }}"
    dest: "{{ iptables_apply__path_buffer }}"
    validate: "iptables-restore --test %s"
  register: iptables_ruleset
