---
# First ensure the resulting file is in good shape when making it available on
# the remote host
- name: rewrite iptables ruleset from scratch
  template:
    src: "{{ iptables_apply__template }}"
    dest: "{{ iptables_apply__path_buffer }}"
    validate: "iptables-restore --test %s"
  register: iptables_ruleset
