---
# First ensure the resulting file is in good shape when making it available on
# the remote host. Do not perform action directly upon the system file nor the
# system state.
- name: "rewrite iptables ruleset's buffer from scratch"
  template:
    src: "{{ iptables_apply__template }}"
    dest: "{{ iptables_apply__path_buffer }}"
    validate: "iptables-restore --test %s"
  register: iptables_ruleset
  when:
    - ( not iptables_apply__template_once|bool ) or
      ( not iptables_apply__template_mark in saved_state.stdout_lines )


# If the buffer is not modified, it remains the same than the backup, so the
# next step will be skipped and this file will not be removed. Do it here.
- name: "remove temporary backup and buffer if unchanged"
  file:
    path: "{{ tempfile }}"
    state: absent
  loop:
    - "{{ iptables_apply__path_backup }}"
    - "{{ iptables_apply__path_buffer }}"
  loop_control:
    loop_var: tempfile
  when:
    - iptables_apply__template_once|bool
    - iptables_apply__template_mark in saved_state.stdout_lines
