---
- name: "delete all rules and reset policies to 'ACCEPT' for all chains"
  template:
    src: "{{ iptables_apply__flush }}"
    dest: "{{ iptables_apply__path_buffer }}"
  register: iptables_apply__ruleset
...
